---
- name: copy my tomcat user on ansible node 
  template: 
    src: template/tomuser.j2
    dest: /opt/tomcat/conf/tomcat-users.xml

- name: copy my tomcat manager user on ansible node
  template: 
    src: template/tommanager.j2
    dest: /opt/tomcat/webapps/manager/META-INF/context.xml

- name: copy my tomcat manager host user on ansible node
  template: 
    src: template/tomhost.j2
    dest: /opt/tomcat/webapps/host-manager/META-INF/context.xml