---
# tasks file for mywebrole2
- name: i want to install webserver on ansible nodes
  apt: 
    name: "{{mywebpackforubuntu}}"
    state: present

- name: i want to install java on RedHat node
  yum: 
    name: "{{myjavapackforredhat}}"
    state: present

- name: i want to copy my index file 
  template: 
    src: template/myindex.j2
    dest: /var/www/html/index.html

    